- name: Configuración inicial de nodos con NFS
  hosts: all
  become: true
  tasks:
    - name: Configurar archivo /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
        state: present
      with_items:
        - "192.168.1.6 master"
        - "192.168.1.7 worker1"
        - "192.168.1.8 worker2"
        - "192.168.1.9 nas"

    - name: Configurar Firewall
      when: inventory_hostname == "nas"
      firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
      with_items:
        - "10250/tcp"
        - "30000-32767/tcp"
        - "179/tcp"
        - "4789/udp"
      notify: reload_firewalld

    - name: Añadir servicio NTP al firewall
      command: firewall-cmd --add-service=ntp --permanent
      notify: reload_firewalld

    - name: Reiniciar NetworkManager
      systemd:
        name: NetworkManager
        state: restarted

    - name: Instalar paquetes adicionales (cliente NFS)
      package:
        name: nfs-utils
        state: present

    - name: Comprobar directorios exportados por el nodo de almacenamiento
      command: showmount -e nas
      register: exported_dirs
      changed_when: false

    - name: Mostrar directorios exportados
      debug:
        msg: "{{ exported_dirs.stdout }}"

    - name: Crear directorios para montaje
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /mnt/web
        - /mnt/post

    - name: Configurar montaje en /etc/fstab
      lineinfile:
        path: /etc/fstab
        line: "{{ item }}"
        state: present
      with_items:
        - "nas:/var/web /mnt/web nfs defaults,_netdev,rw 0 0"
        - "nas:/var/post /mnt/post nfs defaults,_netdev,rw 0 0"

    - name: Recargar configuración del sistema
      command: systemctl daemon-reload

    - name: Montar todos los sistemas de archivos
      command: mount -a

    - name: Verificar sistemas de archivos montados
      command: df -h
      register: mounted_dirs
      changed_when: false

    - name: Mostrar sistemas de archivos montados
      debug:
        msg: "{{ mounted_dirs.stdout }}"

    - name: Probar acceso al directorio /mnt/web
      shell: |
        cd /mnt/web && touch test1 && ls -al
      register: test_web
      changed_when: false

    - name: Mostrar resultados de prueba en /mnt/web
      debug:
        msg: "{{ test_web.stdout }}"

    - name: Reiniciar NetworkManager
      systemd:
        name: NetworkManager
        state: restarted

  handlers:
  - name: reload_firewalld
    command: firewall-cmd --reload

- name: Generar token y unir nodos al clúster Kubernetes
  hosts: master
  become: true
  tasks:
    - name: Guardar comando de unión
      shell: kubeadm token create --print-join-command > /root/join

    - name: Copiar comando join al nodo Ansible
      fetch:
        src: /root/join
        dest: /tmp/join
        flat: yes

- name: Unir NFS al clúster Kubernetes
  hosts: nas
  become: true
  tasks:
    - name: Copiar archivo join desde el nodo Ansible
          copy:
            src: /tmp/join
            dest: /tmp/join

    - name: Unirse al clúster de Kubernetes
      shell: sudo $(cat /tmp/join)