- name: Desinstalación y limpieza de MetalLB en Kubernetes
  hosts: master
  become: true
  tasks:
    #- name: Eliminar ConfigMap de configuración de MetalLB
    #  shell: kubectl delete -f /tmp/metallb-config.yaml

    - name: Eliminar ConfigMap de configuración de MetalLB
      shell: kubectl delete -f /tmp/metallb.yaml