- name: Instalación y configuración de MetalLB en Kubernetes (Layer 2)
  hosts: master
  become: true
  tasks:     
    #- name: Guardar manifiestos de MetalLB en /tmp/namespace-metallb.yaml
      #  get_url:
      #    url: https://raw.githubusercontent.com/metallb/metallb/v0.12.0/manifests/namespace.yaml #https://raw.githubusercontent.com/metallb/metallb/v0.14.8/config/manifests/metallb-native.yaml   #https://raw.githubusercontent.com/metallb/metallb/v0.12.0/manifests/metallb.yaml
      #    dest: /tmp/namespace-metallb.yaml

      #- name: Aplicar manifiestos de namespace MetalLB
      #  shell: kubectl apply -f /tmp/namespace-metallb.yaml
    
    - name: Guardar manifiestos de MetalLB en /tmp/metallb.yaml
      get_url:
        url: https://raw.githubusercontent.com/metallb/metallb/v0.14.9/config/manifests/metallb-native.yaml #https://raw.githubusercontent.com/metallb/metallb/v0.12.0/manifests/metallb.yaml   #https://github.com/metallb/metallb/blob/main/config/manifests/metallb-native.yaml
        dest: /tmp/metallb.yaml

    - name: Aplicar manifiestos de MetalLB
      shell: kubectl apply -f /tmp/metallb.yaml

    - name: Crear ConfigMap de configuración de MetalLB para Layer 2
      copy:
        dest: /tmp/metallb-config.yaml
        content: |
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: config
            namespace: metallb-system
          data:
            config: |
              address-pools:
              - name: default
                protocol: layer2
                addresses:
                - 192.168.1.10-192.168.1.15 # Rango ajustado según la red disponible 

    - name: Aplicar ConfigMap de configuración
      shell: kubectl apply -f /tmp/metallb-config.yaml

    - name: Crear IPAddressPool y L2Advertisement
      copy:
        dest: /tmp/metallb-advanced-config.yaml
        content: |
          apiVersion: metallb.io/v1beta1
          kind: IPAddressPool
          metadata:
            name: first-pool
            namespace: metallb-system
          spec:
            addresses:
            - 192.168.1.10-192.168.1.15 # Rango ajustado según la red disponible
          ---
          apiVersion: metallb.io/v1beta1
          kind: L2Advertisement
          metadata:
            name: example
            namespace: metallb-system

    - name: Aplicar configuración avanzada de MetalLB
      shell: kubectl apply -f /tmp/metallb-advanced-config.yaml

