- name: Instalación y configuración de MetalLB en Kubernetes (Layer 2)
  hosts: master
  become: true
  tasks:     
    - name: Guardar manifiestos de namespace MetalLB en /tmp/namespace-metallb.yaml
      get_url:
        url: https://raw.githubusercontent.com/metallb/metallb/v0.12.1/manifests/namespace.yaml
        dest: /tmp/namespace-metallb.yaml

    - name: Guardar manifiestos de MetalLB en /tmp/metallb.yaml
      get_url:
        url: https://raw.githubusercontent.com/metallb/metallb/v0.14.8/config/manifests/metallb-native.yaml
        dest: /tmp/metallb.yaml

    - name: Aplicar manifiestos de namespace MetalLB
      shell: kubectl apply -f /tmp/namespace-metallb.yaml

    - name: Aplicar manifiestos de MetalLB
      shell: kubectl apply -f /tmp/metallb.yaml

    - name: Crear ConfigMap de configuración de MetalLB para Layer 2
      copy:
        dest: /tmp/metallb-config.yaml
        content: |
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: config
            namespace: metallb-system
          data:
            config: |
              address-pools:
              - name: default
                protocol: layer2
                addresses:
                - 192.168.1.10-192.168.1.15  # Rango ajustado según la red disponible

    - name: Aplicar ConfigMap de configuración
      shell: kubectl create -f /tmp/metallb-config.yaml