- name: Configurar strictARP y modo IPVS en kube-proxy
  hosts: master
  become: yes
  tasks:

    - name: Editar ConfigMap kube-proxy para habilitar strictARP y modo IPVS
      shell: |
        kubectl get configmap kube-proxy -n kube-system -o yaml | \
        sed -e "s/strictARP: false/strictARP: true/" -e "s/mode: \".*\"/mode: \"ipvs\"/" | \
        kubectl apply -f - -n kube-system \
        kubectl delete validatingwebhookconfigurations.admissionregistration.k8s.io metallb-webhook-configuration
      register: apply_result

    - name: Mostrar mensaje de resultado
      debug:
        msg: "Resultado de la aplicación: {{ apply_result.stdout }}"
