- name: Instalaci贸n y configuraci贸n de MetalLB en Kubernetes (Layer 2)
  hosts: master
  become: true
  tasks:
    - name: Crear ConfigMap de configuraci贸n para Layer 2
      copy:
        dest: /tmp/metallb-config.yaml
        content: |
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: config
            namespace: metallb-system
          data:
            config: |
              address-pools:
              - name: external-pool
                protocol: layer2
                addresses:
                - 192.168.1.10-192.168.1.15

    - name: Aplicar ConfigMap de configuraci贸n
      shell: kubectl apply -f /tmp/metallb-config.yaml