- name: Instalaci贸n y configuraci贸n de MetalLB en Kubernetes (Layer 2)
  hosts: master
  become: true
  tasks:
    - name: Descargar manifiestos de MetalLB
      get_url:
        url: https://raw.githubusercontent.com/google/metallb/v0.7.3/manifests/metallb.yaml # https://raw.githubusercontent.com/metallb/metallb/v0.14.9/config/manifests/metallb-native.yaml
        dest: /tmp/metallb.yaml

    - name: Aplicar manifiestos de MetalLB
      shell: kubectl apply -f /tmp/metallb.yaml

    - name: Crear ConfigMap de configuraci贸n para Layer 2
      copy:
        dest: /tmp/metallb-config.yaml
        content: |
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: config
            namespace: metallb-system
          data:
            config: |
              address-pools:
              - name: default
                protocol: layer2
                addresses:
                - 192.168.1.10-192.168.1.15

    - name: Aplicar ConfigMap de configuraci贸n
      shell: kubectl apply -f /tmp/metallb-config.yaml