- name: Instalación y configuración de MetalLB en Kubernetes (Layer 2)
  hosts: master
  become: true
  tasks:
    - name: Descargar manifiestos de MetalLB
      get_url:
        url: https://raw.githubusercontent.com/metallb/metallb/v0.14.9/config/manifests/metallb-native.yaml
        dest: /tmp/metallb.yaml

    - name: Aplicar manifiestos de MetalLB
      shell: kubectl apply -f /tmp/metallb.yaml

    - name: Crear ConfigMap de configuración para Layer 2
      copy:
        dest: /tmp/metallb-config.yaml
        content: |
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: config
            namespace: metallb-system
          data:
            config: |
              address-pools:
              - name: default
                protocol: layer2
                addresses:
                - 192.168.1.10-192.168.1.15

    - name: Aplicar ConfigMap de configuración
      shell: kubectl apply -f /tmp/metallb-config.yaml

    #- name: Crear configuración avanzada de MetalLB
    #  copy:
    #    dest: /tmp/metallb-advanced-config.yaml
    #    content: |
    #      apiVersion: metallb.io/v1beta1
    #      kind: IPAddressPool
    #      metadata:
    #        name: first-pool
    #        namespace: metallb-system
    #      spec:
    #        addresses:
    #        - 192.168.1.10-192.168.1.15
    #      ---
    #      apiVersion: metallb.io/v1beta1
    #      kind: L2Advertisement
    #      metadata:
    #        name: l2-advertisement
    #        namespace: metallb-system
    #      spec:
    #        ipAddressPools:
    #        - first-pool

    #- name: Aplicar configuración avanzada de MetalLB
    #  shell: kubectl apply -f /tmp/metallb-advanced-config.yaml
    #  register: apply_advanced_config_result

    #- name: Verificar estado de los pods tras configuración avanzada
    #  shell: kubectl get pods -n metallb-system
    #  register: check_final_pods
