- name: Setup MetalLB with Helm
  hosts: master
  become: yes

  tasks:
    # 2. Descargar e instalar Helm
    - name: Download Helm installer
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get_helm.sh
        mode: '0755'

    - name: Install Helm
      command: /tmp/get_helm.sh
      args:
        creates: /usr/local/bin/helm

    # 3. Configurar el repositorio de MetalLB
    - name: Add MetalLB Helm repository
      command: helm repo add metallb https://metallb.github.io/metallb
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
      register: helm_add_repo
      changed_when: "'has been added' in helm_add_repo.stdout"

    - name: Update Helm repositories
      command: helm repo update
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/local/bin"

    # 4. Instalar MetalLB
    - name: Download Repo MetalLB with Helm
      command: helm repo add metallb https://metallb.github.io/metallb

    - name: Install MetalLB with Helm
      command: helm install metallb metallb/metallb

