- name: Instalación y configuración de MetalLB en Kubernetes (Layer 2)
  hosts: master
  become: true
  tasks:
    - name: Descargar manifiestos de MetalLB
      get_url:
        url: https://raw.githubusercontent.com/metallb/metallb/v0.14.8/config/manifests/metallb-native.yaml
        dest: /tmp/metallb.yaml

    - name: Aplicar manifiestos de MetalLB
      shell: kubectl apply -f /tmp/metallb.yaml

    - name: Crear ConfigMap de configuración de MetalLB para Layer 2
      copy:
        dest: /tmp/metallb-config.yaml
        content: |
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: config
            namespace: metallb-system
          data:
            config: |
              address-pools:
                - name: default
                  protocol: layer2
                  addresses:
                    - 192.168.1.7-192.168.1.8  # Ajusta el rango de IP según tu red

    - name: Aplicar ConfigMap de configuración
      shell: kubectl apply -f /tmp/metallb-config.yaml

    - name: Comprobar estado de los pods de MetalLB
      command: kubectl get pods -n metallb-system
      register: metallb_pods
      changed_when: false

    - name: Mostrar estado de los pods de MetalLB
      debug:
        msg: "{{ metallb_pods.stdout }}"

    - name: Eliminar archivo temporal de configuración
      file:
        path: /tmp/metallb-config.yaml
        state: absent
