- name: Instalación y configuración de MetalLB en Kubernetes (Layer 2)
  hosts: master
  become: true
  tasks:
    - name: Descargar manifiestos de MetalLB
      get_url:
        url: https://raw.githubusercontent.com/metallb/metallb/v0.14.9/config/manifests/metallb-native.yaml # https://raw.githubusercontent.com/metallb/metallb/v0.14.9/config/manifests/metallb-native.yaml # https://raw.githubusercontent.com/google/metallb/v0.7.3/manifests/metallb.yaml 
        dest: /tmp/metallb.yaml

    - name: Aplicar manifiestos de MetalLB
      shell: kubectl apply -f /tmp/metallb.yaml