- name: Instalación y configuración de MetalLB en Kubernetes (Layer 2)
  hosts: master
  become: true
  tasks:
    - name: Añadir el repositorio de Helm (si no está añadido)
      shell: |
        helm repo add metallb https://metallb.github.io/metallb
        helm repo update
      when: ansible_facts.packages['helm'] is not defined

    - name: Instalar MetalLB usando Helm
      helm:
        name: metallb
        chart: metallb/metallb
        namespace: metallb-system
        create_namespace: true
        version: "v0.13.7"  # Ajusta la versión según sea necesario
        state: present
      register: metallb_install

    - name: Comprobar si MetalLB se instaló correctamente
      debug:
        msg: "MetalLB instalado correctamente en el clúster"
      when: metallb_install is changed

    - name: Crear ConfigMap de configuración de MetalLB para Layer 2
      copy:
        dest: /tmp/metallb-config.yaml
        content: |
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: config
            namespace: metallb-system
          data:
            config: |
              address-pools:
                - name: default
                  protocol: layer2
                  addresses:
                    - 192.168.1.7-192.168.1.8  # Rango de IP para asignar a LoadBalancer (solo 192.168.1.7 y 192.168.1.8)
      when: metallb_install is changed

    - name: Aplicar ConfigMap de configuración de MetalLB
      kubectl:
        command: apply
        file: /tmp/metallb-config.yaml
      when: metallb_install is changed

    - name: Comprobar estado de los pods de MetalLB
      command: kubectl get pods -n metallb-system
      register: metallb_pods
      changed_when: false

    - name: Mostrar estado de los pods de MetalLB
      debug:
        msg: "{{ metallb_pods.stdout }}"

    - name: Eliminar archivo temporal de configuración
      file:
        path: /tmp/metallb-config.yaml
        state: absent
      when: metallb_install is changed

    - name: Comprobar que MetalLB se está ejecutando correctamente en el nodo master
      command: kubectl get pods -n metallb-system -o wide
      register: metallb_status
      changed_when: false

    - name: Mostrar el estado de los pods de MetalLB en el nodo master
      debug:
        msg: "{{ metallb_status.stdout }}"
