- name: Aplicar configuración de NGINX y HPA en el master
  hosts: master  
  become: true
  tasks:
    - name: Aplicar nginx-deployment.yaml
      shell: kubectl apply -f deployment.yml
      
    - name: Aplicar nginx-service.yaml
      shell: kubectl apply -f service.yml

    - name: Aplicar nginx-hpa.yaml
      shell: kubectl apply -f hpa.yml

    - name: Verificar los Pods y Servicios
      shell: kubectl get pods,services,hpa
      register: kubectl_output
      ignore_errors: yes

    - name: Mostrar el resultado de kubectl
      debug:
        var: kubectl_output.stdout
