- name: Instalación y configuración de Metrics Server con Helm
  hosts: master
  become: true
  tasks:
    - name: Instalar paquetes necesarios (tar y curl)
      package:
        name: 
          - tar
          - curl
        state: present

    - name: Instalar Helm si no está instalado
      shell: |
        if ! command -v helm &> /dev/null; then
          curl -fsSL -o /tmp/helm.tar.gz https://get.helm.sh/helm-v3.13.0-linux-amd64.tar.gz
          tar -xzf /tmp/helm.tar.gz -C /tmp
          mv /tmp/linux-amd64/helm /usr/local/bin/helm
        fi
      args:
        executable: /bin/bash

    - name: Agregar el repositorio de Helm para Metrics Server
      shell: helm repo add metrics-server https://kubernetes-sigs.github.io/metrics-server/

    - name: Actualizar los repositorios de Helm
      shell: helm repo update

    - name: Instalar o actualizar el Metrics Server
      shell: >
        helm upgrade --install metrics-server metrics-server/metrics-server
        --set args={--kubelet-insecure-tls}
