- name: Instalaci칩n y configuraci칩n de Metrics Server en namespace metallb-system
  hosts: master
  become: true
  tasks:
    - name: Descargar manifiesto de Metric Server (modo est치ndar)
      ansible.builtin.get_url:
        url: https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
        dest: /tmp/components.yaml

    - name: Descargar manifiesto de Metric Server (modo alta disponibilidad)
      ansible.builtin.get_url:
        url: https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/high-availability-1.21+.yaml
        dest: /tmp/high-availability.yaml

    - name: Modificar archivo YAML de Metrics Server
      block:
        - name: Agregar par치metros al archivo YAML
          lineinfile:
            path: /tmp/components.yaml
            insertafter: "- --secure-port=4443"
            line: "          - --kubelet-insecure-tls"

        - name: Agregar hostNetwork a spec
          replace:
            path: /tmp/components.yaml
            regexp: "spec:"
            replace: "spec:\n  hostNetwork: true"

    #- name: Desplegar Metrics Server
    #  command: "kubectl apply -f /tmp/components.yaml"
