- name: Instalación y configuración de metric server en namespace metallb-system
  hosts: master
  become: true
  tasks:
    - name: Descargar manifiesto de Metric Server
      get_url:
        url: https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
        dest: /tmp/metrics-server.yaml

    - name: Aplicar manifiesto de Metric Server
      shell: kubectl apply -f /tmp/metrics-server.yaml

    - name: Parchear deployment de Metric Server
      shell: |
        kubectl patch deployment metrics-server -n metallb-system --type='json' -p='[
        {
        "op": "add",
        "path": "/spec/template/spec/hostNetwork",
        "value": true
        },
        {
        "op": "replace",
        "path": "/spec/template/spec/containers/0/args",
        "value": [
        "--cert-dir=/tmp",
        "--secure-port=4443",
        "--kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname",
        "--kubelet-use-node-status-port",
        "--metric-resolution=15s",
        "--kubelet-insecure-tls"
        ]
        },
        {
        "op": "replace",
        "path": "/spec/template/spec/containers/0/ports/0/containerPort",
        "value": 4443
        }
        ]'