apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
spec:
  selector:
    app: nginx  # Se asocia con los pods que tienen esta etiqueta
  ports:
    - protocol: TCP
      port: 80  # Puerto que escucharán los pods
      targetPort: 80  # Puerto dentro del contenedor
      nodePort: 30080  # Puerto expuesto en el nodo (ajusta si es necesario)
  type: NodePort