- name: Aplicar metric server a Master
  hosts: master  
  become: true
  tasks:
    - name: Copiar
      copy:
        src: ~/ansible/nfs/web/metricserver.txt  # Ruta en el nodo Ansible
        dest: /tmp/metricserver