- name: Copiar todos los yaml de la web personalizada, deployment, service y hpa en el master
  hosts: master  
  become: true
  tasks:
    - name: Copiar deploy.yaml al master
      copy:
        src: ~/ansible/nfs/web/deploy.yaml  # Ruta en el nodo Ansible
        dest: /tmp/deploy.yaml                    # Ruta en el master

    - name: Copiar pv.yaml al master
      copy:
        src: ~/ansible/nfs/web/pv.yaml   # Ruta en el nodo Ansible
        dest: /tmp/pv.yaml                      # Ruta en el master

    - name: Copiar pvc.yaml al master
      copy:
        src: ~/ansible/nfs/web/pvc.yaml       # Ruta en el nodo Ansible
        dest: /tmp/pvc.yaml                          # Ruta en el master

    - name: Copiar service.yaml al master
      copy:
        src: ~/ansible/nfs/web/service.yaml  # Ruta en el nodo Ansible
        dest: /tmp/service.yaml                    # Ruta en el master

    - name: Copiar hpa.yaml al master
      copy:
        src: ~/ansible/nfs/web/hpa.yaml  # Ruta en el nodo Ansible
        dest: /tmp/hpa.yaml                    # Ruta en el master