apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: metallb-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: web-volume
        persistentVolumeClaim:
          claimName: web-pvc