- name: Aplicar index.php a NFS
  hosts: nas  
  become: true
  tasks:
    - name: Copiar
      copy:
        src: ~/ansible/nfs/index.php  # Ruta en el nodo Ansible
        dest: /var/web.yaml                    # Ruta en el master