apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-pv
spec:
  storageClassName: storage-nfs
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /var/web
    server: 192.168.1.9
    readOnly: no