apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: metallb-system
spec:
  selector:
    app: nginx  # Se asocia con los pods que tienen esta etiqueta
  ports:
    - name: http
      protocol: TCP
      port: 8080  # Puerto que escucharán los pods
      targetPort: 8080  # Puerto dentro del contenedor
  type: LoadBalancer
  externalTrafficPolicy: Local