- name: Aplicar configuración de Kubernetes
  hosts: master
  become: true
  tasks:
    - name: Aplicar PersistentVolume (pv.yaml)
      shell: kubectl apply -f /tmp/pv.yaml

    - name: Aplicar PersistentVolumeClaim (pvc.yaml)
      shell: kubectl apply -f /tmp/pvc.yaml

    - name: Aplicar Deployment (deploy.yaml)
      shell: kubectl apply -f /tmp/deploy.yaml

    - name: Aplicar Service (service.yaml)
      shell: kubectl apply -f /tmp/service.yaml

    - name: Aplicar Horizontal Pod Autoscaler (hpa.yaml)
      shell: kubectl apply -f /tmp/hpa.yaml