- name: Instalar containerd
  hosts: k8s
  become: yes
  tasks:
    - name: Añadir repositorio Docker
      command: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: Instalar containerd
      yum:
        name: containerd.io
        state: present

    - name: Configurar containerd
      copy:
        dest: /etc/containerd/config.toml
        content: "{{ lookup('pipe', 'containerd config default') | regex_replace('SystemdCgroup = false', 'SystemdCgroup = true') }}"
      notify: restart containerd

  handlers:
    - name: restart containerd
      service:
        name: containerd
        state: restarted
        enabled: true
