- name: Configuración inicial de nodos con NFS
  hosts: all
  become: true
  tasks:
    - name: Configurar archivo /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
        state: present
      with_items:
        - "192.168.1.6 master"
        - "192.168.1.7 worker1"
        - "192.168.1.8 worker2"
        - "192.168.1.9 nas"

    - name: Configurar Firewall
      when: inventory_hostname == "nas"
      firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
      with_items:
        - "10250/tcp"
        - "30000-32767/tcp"
        - "179/tcp"
        - "4789/udp"
      notify: reload_firewalld

    - name: Añadir servicio NTP al firewall
      command: firewall-cmd --add-service=ntp --permanent
      notify: reload_firewalld

    - name: Reiniciar NetworkManager
      systemd:
        name: NetworkManager
        state: restarted

  handlers:
  - name: reload_firewalld
    command: firewall-cmd --reload
