- name: Inicialización del Clúster y Configuración de Calico
  hosts: master  # Se aplica solo al nodo master
  become: true
  tasks:

    - name: Inicializar Kubernetes en el nodo master
      command: kubeadm init --pod-network-cidr=172.16.0.0/12
      register: kubeadm_init_output

    - name: Configurar acceso a kubectl
      block:
        - name: Crear directorio para kubectl
          file:
            path: "{{ ansible_env.HOME }}/.kube"
            state: directory
            mode: '0700'

        - name: Copiar configuración de kubeadm al directorio de kubectl
          copy:
            src: /etc/kubernetes/admin.conf
            dest: "{{ ansible_env.HOME }}/.kube/config"
            remote_src: yes

        - name: Cambiar propietario del archivo kube/config
          file:
            path: "{{ ansible_env.HOME }}/.kube/config"
            owner: "{{ ansible_user }}"
            group: "{{ ansible_user }}"
            mode: '0600'

    - name: Crear el comando de unión para nodos worker
      command: kubeadm token create --print-join-command
      register: join_command_output

    - name: Guardar el comando de unión en el archivo
      copy:
        content: "{{ join_command_output.stdout }}"
        dest: "/root/join"
        mode: '0600'

- name: Copiar el comando join a los nodos worker
  hosts: workers
  become: true
  tasks:
    - name: Copiar archivo join desde el master
      fetch:
        src: "/root/join"
        dest: "/tmp/join"
        flat: yes

    - name: Unirse al clúster de Kubernetes
      command: "sudo $(cat /tmp/join)"
      when: "'join' in lookup('file', '/tmp/join')"

- name: Configuración de la Red (Calico)
  hosts: master  # Solo en el nodo master
  become: true
  tasks:
    - name: Descargar el archivo de configuración de Calico
      get_url:
        url: https://docs.projectcalico.org/manifests/calico.yaml
        dest: /tmp/calico.yaml

    - name: Configurar Calico en el archivo descargado
      lineinfile:
        path: /tmp/calico.yaml
        regexp: 'value: "192.168.0.0/16"'
        line: '        value: "172.16.0.0/12"'

    - name: Aplicar la configuración de Calico
      command: kubectl apply -f /tmp/calico.yaml
