- name: Copiar el comando join a los nodos worker
  hosts: workers
  become: true
  tasks:

    - name: Copiar archivo join desde el nodo Ansible
      copy:
        src: /tmp/join
        dest: /tmp/join

    - name: Unirse al clúster de Kubernetes
      command: "$(cat /tmp/join)"
      when: "'join' in lookup('file', '/tmp/join')"

- name: Configuración de la Red (Calico)
  hosts: master  # Solo en el nodo master
  become: true
  tasks:
    - name: Descargar el archivo de configuración de Calico
      get_url:
        url: https://docs.projectcalico.org/manifests/calico.yaml
        dest: /tmp/calico.yaml

    - name: Configurar Calico en el archivo descargado
      lineinfile:
        path: /tmp/calico.yaml
        regexp: 'value: "192.168.0.0/16"'
        line: '        value: "172.16.0.0/12"'

    - name: Aplicar la configuración de Calico
      command: kubectl apply -f /tmp/calico.yaml