apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-pvc
  namespace: metallb-system
spec:
  storageClassName: storage-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: web-pv
