apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: metallb-system
spec:
  selector:
    app: nginx  # Se asocia con los pods que tienen esta etiqueta
  ports:
    - name: http
      protocol: TCP
      port: 80  # Puerto que escucharán los pods
      targetPort: 80  # Puerto dentro del contenedor
  type: LoadBalancer
  #loadBalancerIP: 192.168.1.11  # Una IP del external-pool
  externalTrafficPolicy: Cluster # Local