- name: Setup MetalLB with Helm
  hosts: master
  become: yes

  tasks:
    # 0. Instalar tar si no está disponible
    - name: Install tar
      package:
        name: tar
        state: present

    # 1. Descargar el binario de Helm
    - name: Download the latest Helm binary
      get_url:
        url: https://get.helm.sh/helm-v3.16.1-linux-amd64.tar.gz
        dest: /tmp/helm-linux-amd64.tar.gz

    # 2. Extraer el binario descargado
    - name: Extract Helm binary using the tar command
      command: tar -zxvf /tmp/helm-linux-amd64.tar.gz -C /tmp/
      args:
        creates: /tmp/linux-amd64

    # 3. Mover el binario a /usr/local/bin
    - name: Move Helm binary to /usr/local/bin
      command: mv /tmp/linux-amd64/helm /usr/local/bin/helm
      args:
        creates: /usr/local/bin/helm

    # 4. Verificar la instalación de Helm
    - name: Verify Helm installation
      command: helm version
      register: helm_version_output

    # 5. Añadir el repositorio de MetalLB
    - name: Add MetalLB Helm repository
      command: helm repo add metallb https://metallb.github.io/metallb
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/local/bin"

    # 6. Actualizar los repositorios de Helm
    - name: Update Helm repositories
      command: helm repo update
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/local/bin"

    # 7. Instalar MetalLB con Helm usando un archivo values.yaml
    - name: Install MetalLB with Helm
      command: helm install metallb metallb/metallb --namespace metallb-system --create-namespace --set crds.create=true --set metrics.enabled=false # helm install metallb metallb/metallb --namespace metallb-system --create-namespace
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/local/bin"

    # 8. Etiquetar el namespace metallb-system para permisos elevados usando shell
    - name: Label the metallb-system namespace for privileged pods
      shell: |
        kubectl label namespace metallb-system pod-security.kubernetes.io/enforce=privileged --overwrite
        kubectl label namespace metallb-system pod-security.kubernetes.io/audit=privileged --overwrite
        kubectl label namespace metallb-system pod-security.kubernetes.io/warn=privileged --overwrite