- name: Aplicar configuración de NGINX y HPA en el master
  hosts: master  
  become: true
  tasks:
    - name: Copiar nginx-deployment.yaml al master
      copy:
        #src: ~/ansible/nfs/deployment.yaml  # Ruta en el nodo Ansible
        src: ~/ansible/nfs/deploymentClaim.yaml  # Ruta en el nodo Ansible
        dest: /tmp/deployment.yaml                    # Ruta en el master

    - name: Copiar nginx-service.yaml al master
      copy:
        src: ~/ansible/nfs/service.yaml   # Ruta en el nodo Ansible
        dest: /tmp/service.yaml                      # Ruta en el master

    - name: Copiar nginx-hpa.yaml al master
      copy:
        src: ~/ansible/nfs/hpa.yaml       # Ruta en el nodo Ansible
        dest: /tmp/hpa.yaml                          # Ruta en el master

    - name: Aplicar nginx-deployment.yaml
      shell: kubectl apply -f /tmp/deployment.yaml
      #shell: kubectl apply -f /tmp/deploymentClaim.yaml

    - name: Aplicar nginx-service.yaml
      shell: kubectl apply -f /tmp/service.yaml

    - name: Aplicar nginx-hpa.yaml
      shell: kubectl apply -f /tmp/hpa.yaml

    - name: Verificar los Pods y Servicios
      shell: kubectl get pods,services,hpa
      register: kubectl_output
      ignore_errors: yes

    - name: Mostrar el resultado de kubectl
      debug:
        var: kubectl_output.stdout
