apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-pv
spec:
  storageClassName: storage-nfs
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /var/web
    server: 192.168.1.9
    readOnly: no

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-pvc
  namespace: metallb-system
spec:
  storageClassName: storage-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: web-pv

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: metallb-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: web-volume
        persistentVolumeClaim:
          claimName: web-pvc
      #affinity:
      #  nodeAffinity:
      #    requiredDuringSchedulingIgnoredDuringExecution:
      #      nodeSelectorTerms:
      #        - matchExpressions:
      #            - key: kubernetes.io/hostname
      #              operator: In
      #             values:
      #               - worker1
      #               - worker2
